### ISSUE TITLE
转换好像有问题，yolox不行训练

### ISSUE THREAD

**Issue by Robert-Hopkins** [RapidAI/YOLO2COCO#2]

**Comment by songtf525** [comment]
YOLO2COCO生成的json中，annotations内的id应该是唯一的，即每一个目标都应该是唯一的，这里他给的是每一张图是唯一的，所以需要把annotation_id设定为全局，或者你自己设计调用，只要 id: annotation_id 中这个annotation_id能唯一

**Comment by SWHL** [comment]
- `annotation_id`已经设定为全局
- 这次应该没有问题
