### ISSUE TITLE
little improvement suggestion

### ISSUE THREAD

**Issue by KaizerJ** [RapidAI/YOLO2COCO#5]
Hello. Right now [yolov5_2_coco.py](https://github.com/RapidAI/YOLO2COCO/blob/main/yolov5_2_coco.py) script demands that train.txt paths must be absolute paths to the images. That's not very common in yolo like datasets. I suggest to change line 119 to
`img_path = Path(self.raw_data_dir / img_path)` to use relatives paths instead or even check if the path is relative or absolute to treat it properly.

**Comment by SWHL** [comment]
- Thanks, LGTM. I have accepted your suggestion, see for details:
https://github.com/RapidAI/YOLO2COCO/blob/0823c193cb1fe9d0b25e345be6fdef5ffce7767e/yolov5_2_coco.py#L120-L123
